### ISSUE TITLE
Data18-Content Scraper only works with Data 18 Content ID's not Strings

### ISSUE THREAD

**Issue by alexholliz** [chidychi/Data18-Content.bundle#23]
Using the latest code from github, just reinstalled the scrapers after I noticed this behavior, it still does it.

The matching works fine, if the search term is the content ID, like "1164676". But doesn't work if you use the actual content title.

I'm happy to grab logs to help debug, but I don't know where those are.

**Comment by alexholliz** [comment]
Update, I just tested it with two more scenes, and one of them worked with just the filename being the title of the scene, while another didn't.

Worked: http://www.data18.com/content/1161390
Didn't: www.data18.com/content/1161530

**Comment by lazeraman** [comment]
The search is based off of Data18's search function.  The search does appears to be having issues atm. At least in my testing getting results has been intermittent. I think they may be having issues as I can get some of mine to work. Might be coming back up now as more of my test searches are working.

**Comment by alexholliz** [comment]
I think you're right, sometimes it works and sometimes it doesn't. Just searching on Data18 by itself will occasionally throw a "too many requests" error
