### ISSUE TITLE
Sometimes wont find metadata even with correct filename.

### ISSUE THREAD

**Issue by bryanlyon** [chidychi/Data18-Content.bundle#3]
This happens with a variety of cases.  I can't find all the reasons.  Here are some that I've found

The filenames match the name on the page
/content/1135960
/content/1138334
/content/1138550
/content/1136043

Plex Version 2.2.7
Running on: Linux Superm 3.11.0-26-generic #45-Ubuntu SMP Tue Jul 15 04:02:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by chidychi** [comment]
Sorry for the extremely late reply.

There was a post in July on the plex forums regarding this.  If you can't search for the title using the regular search than try renaming your filenames to something like this.
/content/1135960 would be "Dillon Harper in Tiny4k (2014) - Sporty Babe.avi"
You WILL get mismatches; however that is the only way we can get it in the search results.

https://forums.plex.tv/index.php/topic/66061-adult-data18com-metadata-agent-release/?p=678421
